### ISSUE TITLE
Certificates are not renewed

### ISSUE THREAD

**Issue by gw0** [tozd/docker-nginx-proxy#10]
It seems that Let's encrypt certificates do not get automatically renewed if no changes are made to `/ssl/letsencrypt.list`.

Logs in `/var/log/dockergen/current` are full of:

```
2016-08-26_06:43:21.31882 2016/08/26 06:43:21 Contents of /ssl/letsencrypt.list did not change. Skipping notification '/letsencrypt/dockergen.sh'
```

Workaround is to write something in `/ssl/letsencrypt.list`, manually run `/letsencrypt/dockergen.sh` and afterwards remove the changes.

**Comment by mitar** [comment]
No, there is some strange bug I do not know why it happens. So cron does not seem to run its daily cronjob. If you run it manually, it works without problems.
